apiVersion: v1
kind: ServiceAccount
metadata:
  name: asset-manager-prod-ksa
  namespace: asset-manager-prod
  annotations:
    iam.gke.io/gcp-service-account: asset-manager-prod-sa@ethans-services.iam.gserviceaccount.com
