apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-manager
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: asset-manager-staging-ksa
      containers:
        - name: asset-manager
          envFrom:
            - configMapRef:
                name: asset-manager-config
            - configMapRef:
                name: asset-manager-staging-env-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: asset-manager-staging-secrets
                  key: DATABASE_URL
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: asset-manager-staging-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: asset-manager-staging-secrets
                  key: CLIENT_SECRET
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: asset-manager-staging-secrets
                  key: SECRET_KEY
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: asset-manager-staging-secrets
