apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: asset-manager-staging-secrets
  namespace: asset-manager-staging
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/ethans-services/secrets/asset_manager_staging_database_url/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/ethans-services/secrets/asset_manager_staging_client_id/versions/latest"
        path: "CLIENT_ID"
      - resourceName: "projects/ethans-services/secrets/asset_manager_staging_client_secret/versions/latest"
        path: "CLIENT_SECRET"
      - resourceName: "projects/ethans-services/secrets/asset_manager_staging_secret_key/versions/latest"
        path: "SECRET_KEY"
  secretObjects:
    - secretName: asset-manager-staging-secrets
      type: Opaque
      data:
        - objectName: "DATABASE_URL"
          key: DATABASE_URL
        - objectName: "CLIENT_ID"
          key: CLIENT_ID
        - objectName: "CLIENT_SECRET"
          key: CLIENT_SECRET
        - objectName: "SECRET_KEY"
          key: SECRET_KEY
