apiVersion: v1
kind: ServiceAccount
metadata:
  name: asset-manager-staging-ksa
  namespace: asset-manager-staging
  annotations:
    iam.gke.io/gcp-service-account: asset-manager-staging-sa@ethans-services.iam.gserviceaccount.com
