apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: asset-manager-staging
  namespace: argocd
spec:
  namespace: argocd
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: asset-manager-staging
      images:
        - alias: asset-manager
          imageName: us-central1-docker.pkg.dev/ethans-services/containers/asset-manager
          commonUpdateSettings:
            updateStrategy: newest-build
